automation_action_uuid: 245b3f58-0a4f-49c1-8b48-73c3b43673b6
automation_module_uuid: 0b8e1ea4-f191-4486-9658-47578a67d046
product: sekoia
role: trigger
target_product: mwdb
topic: config_to_observables
