automation_action_uuid: 97d8da42-a30e-4ece-931e-cf912aec5048
automation_module_uuid: e2215979-3462-4fb6-8635-57700aada01c
product: sekoia
role: trigger
target_product: panda_security
topic: links_devices_to_a_managed_configuration_
