automation_action_uuid: fb034867-7d29-4c58-aedb-758bb1047b22
automation_module_uuid: e2215979-3462-4fb6-8635-57700aada01c
product: sekoia
role: trigger
target_product: panda_security
topic: retrieves_a_list_of_managed_configurations_
